### ISSUE TITLE
allow setting waiting timeout for kapp deploy/delete

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#15]
currently it will continue to wait indefinitely. @DTTerastar proposes to have 15min default timeout with a possible configuration.

**Comment by cppforlife** [comment]
added --apply-wait-timeout in https://github.com/k14s/kapp/commit/283dd9c9b7dfe2ec6ed8907bab21fbba6a8c8e99

**Comment by SachithKasthuriarachchi** [comment]
@cppforlife I couldn't use this new flag on v0.52.0 release. Has it been removed?

**Comment by praveenrewar** [comment]
Hey @SachithKasthuriarachchi !
We now have `--apply-timeout` and `--wait-timeout` instead of `--apply-wait-timeout`, and `--apply-check-interval` and `--wait-check-interval` instead of `--apply-wait-check-interval` (I think since v0.10.0).
You can take a look at the description by using `kapp deploy --help`.

**Comment by SachithKasthuriarachchi** [comment]
@praveenrewar thanks a lot for the clarification!
