### ISSUE TITLE
Add FAQ: what is the best way to migrate from `kubectl apply` to kapp?

### ISSUE THREAD

**Issue by jstrachan** [k14s/kapp#204]
we've been trying out `kapp` on the [Jenkins X](https://jenkins-x.io/) project inside a GitOps pipeline and so far its been working really well - thanks!

we'd love to make `kapp` the default going forwards instead of `kubectl apply` - but to do that we need to figure out a way for folks to upgrade their clusters from a `kubectl apply` based setup to a `kapp` based one.

I tried moving an existing cluster setup via `kubectl apply` to use `kapp` and it seems kapp modifies `Deployment` `spec.selector` labels with a kapp based selector label which kubernetes then rejects.

So I wondered is there a canonical way to migrate resources to `kapp` that we should be using?  Would love to figure out a simple way folks can move to kapp; ideally without having to delete all the kubernetes resources first

**Comment by gcheadle-vmware** [comment]
Hi @jstrachan,

 > I tried moving an existing cluster setup via kubectl apply to use kapp and it seems kapp modifies Deployment spec.selector labels with a kapp based selector label which kubernetes then rejects.

Yes, we have seen this problem before. Deployment resources can have immutable fields (spec.selector) that kapp will try and update. For this case, you can add the `kapp.k14s.io/disable-default-label-scoping-rules: ""` annotation as a [kapp configuration](https://carvel.dev/kapp/docs/latest/config/) to prevent kapp from touching the immutable fields when adopting a resource.

> So I wondered is there a canonical way to migrate resources to kapp that we should be using? 

We are currently working on adding a FAQ item to the kapp documentation so that this process will be easier for users in the future.

Additional Resources:
- [Label Scoping Rules doc link](https://carvel.dev/kapp/docs/latest/config/#labelscopingrules)
- [Relevant question asked in K8s public slack](https://kubernetes.slack.com/archives/CH8KCCKA5/p1606079730457700)


Let us know if this helps, or if you have any more questions.

**Comment by aaronshurley** [comment]
@jstrachan does the above help? Please let us know if you need any further assistance or if we can close this issue.

**Comment by gcheadle-vmware** [comment]
@aaronshurley Keeping this issue open as a tracker for adding the question to FAQ doc.

**Comment by gabegorelick** [comment]
https://github.com/vmware-tanzu/carvel.dev/pull/84 added the mentioned [FAQ entry](https://carvel.dev/kapp/docs/latest/faq/#migrating-from-kubectl-apply-to-kapp):

> To prevent this failure, add the kapp.k14s.io/disable-default-label-scoping-rules: "" annotation as a kapp configuration to prevent kapp from touching the immutable fields when adopting a resource.

But I am confused why kapp doesn't handle this by default instead of erroring out.

**Comment by cari-lynn** [comment]
When trying to update label selectors kapp will error when adopting existing resources not deployed by kapp and the person deploying currently needs to decide what strategy that is best for them to fall back on. 

I can think of two strategies to choose from:
- Not update label selectors (using kapp.k14s.io/disable-default-label-scoping-rules: ""`). This has no effect on kapp's ability to track resources but must be added to the annotations on each resource that it is needed for.
- Delete and update the resource (via `kapp.k14s.io/update-strategy: fallback-on-replace` annotation) so that the label selectors can be applied. This has downtime implications.

The decision to require updating these immutable fields was made to add labels that may be helpful in grouping resources. However, with what we know now and that this isn't a required feature of kapp, we may want to reevaluate this and look for a way to make it 'opt-in' instead. Although, this may have implications for backwards compatibility so we may want to consider adding a flag to to change this behavior.

**Comment by pivotaljohn** [comment]
It wasn't 100% clear to me, reviewing this issue, but here's the status as of now:

- [x] as @gabegorelick said, the FAQ requested by this issue _was_ written an merged in vmware-tanzu/carvel.dev#84  
- [x] @cari-lynn captured the desire for a better out-of-the-box experience with #214; how we go about doing this will be worked through _that_ issue.
