### ISSUE TITLE
List all kapp namespaces

### ISSUE THREAD

**Issue by eduardoroliveira** [k14s/kapp#206]
**Describe the problem/challenge you have**
It would be difficult in a big environment to know what namespaces belong to kapp app, also the `kapp ls` only lists a single namespace.

**Describe the solution you'd like**
 It would be wonderful for have the kapp `ls -A` option to list all namespaces.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Comment by danielhelfand** [comment]
It does appear as if `kapp ls -A` is only showing one namespace in the namespace column:

```
kapp ls -A 
Target cluster 'https://127.0.0.1:32784' (nodes: minikube)

Apps in all namespaces

Namespace  Name  Namespaces                 Lcs    Lca  
default    app   foo                        false  55s  
^          kc    (cluster),kapp-controller  true   11m  
^          rbac  (cluster),default          true   10m  

```

@eduardoroliveira Is your proposal here to appropriately populate the namespaces column of `kapp ls -A`?

**Comment by aaronshurley** [comment]
hey @eduardoroliveira, any thoughts on the above question?

**Comment by joaopapereira** [comment]
I deployed using `kapp` a couple of manifests in different namespaces and this is the output:
```
$ kapp ls -A
Target cluster 'https://127.0.0.1:61076' (nodes: kind-control-plane)

Apps in all namespaces

Namespace  Name                      Namespaces                 Lcs   Lca
default    demo-1-setup              (cluster),demo-1-ns        true  11s
^          demo-2-setup              (cluster),demo-2-ns        true  11s
^          demo-3-setup              (cluster),demo-3-ns        true  11s
^          installed-package-bundle  demo-2-ns                  true  4s
^          kc                        (cluster),kapp-controller  true  4m
^          package-bundle            (cluster)                  true  27s
demo-2-ns  hello-world-1-0-0-ctrl    demo-2-ns                  -     0s

Lcs: Last Change Successful
Lca: Last Change Age

7 apps

Succeeded
```
Looks like what is represented as `Namespace` in that column on the left is the place where the config-map that `kapp` uses to manage the deployment is placed.
If you notice the last one you will see that is the only one that has a namespace that is different from `default` and that happens because the application was created by `kapp-controller` and the config-map is present in that particular namespace.

But back to the original questions, it looks like `kapp ls -A` is able to display all the deployments created by `kapp` in any namespace.

I assume that this answer you request @eduardoroliveira?

**Comment by joaopapereira** [comment]
Just another piece of information if you want these ConfigMaps to be created in a different namespace you can provide the `-n` flag when doing the deploy, and `kapp` will create the ConfigMap in that particular namespace. This way the first column of the output for `kapp ls -A` will have a different value.

**Comment by pivotaljohn** [comment]
This ambiguity in the UI has yielded two issues and who knows how much unchecked confusion.
Addressing this with #217.

Marked this as "helping-with-an-issue" — because it was about explaining a confusing UI, not that the tool doesn't have the feature.

@eduardoroliveira, if you would like more support, please do not hesitate to request here or in [Slack](https://kubernetes.slack.com/archives/CH8KCCKA5).
