### ISSUE TITLE
kapp inspect --raw should not generate header/footer informational message to stdout

### ISSUE THREAD

**Issue by GrahamDumpleton** [k14s/kapp#239]
**What steps did you take:**

Run:

```
kapp inspect -a example --raw > resources.yaml
```

**What happened:**

This generates all the resources making up the application deployment, but the header/footer information messages are also generated to stdout, meaning they end up in the yaml file with the resources. This makes it impossible to then do further processing on the YAML file without first editing the file to remove the messages.

Eg., file contains:

```
Target cluster 'https://vcluster.lab-package-testing-w01-s013-vc.svc.cluster.local' (nodes: kind-control-plane)

---
apiVersion: apps/v1
...

Succeeded
```

**What did you expect:**

The header/footer should either not be generated at all, or should be generated to stderr instead.

This would then allow processing of resulting YAML file, including being able to pipe it directly into other commands.

Eg.

```
kapp inspect -a example --raw | kbld inspect -f -
```

**Anything else you would like to add:**

Nope.

**Environment:**

```
$ kapp --version
kapp version 0.37.0
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

cc @jorgemoralespou

**Comment by GrahamDumpleton** [comment]
Pointed out to me can do:

```
kapp inspect -a example --raw --tty=false | kbld inspect -f -
```

But still believe the purpose of ``--raw`` option should imply that the header/footer should not get in the way to begin with.

**Comment by GrahamDumpleton** [comment]
The simple solution to this would be that it auto detects when output is not a tty and implicitly set ``--tty=false`` instead of it being hardwired.

**Comment by aaronshurley** [comment]
For some context, [the code](https://github.com/vmware-tanzu/carvel-kapp/blob/3f3e207d7198cdedd6985761ecb0d9616a84e305/pkg/kapp/cmd/ui_flags.go#L19-L20) points out to [an issue](https://github.com/vmware-tanzu/carvel-kapp/issues/28) that briefly describes why `--tty` was set to `true` by default.

_I think_ that there's a bit to unpack here to ensure that we take a consistent and holistic approach to configuring these flags properly. I'm going to mark this issue as `carvel accepted` but also add the `discussion` label so that we can further hash out the details.

I'm not sure when this issue will be prioritized for the maintainers to work. If anyone is interested in contributing this work, please let us know so that we further drive out the definition here.

**Comment by rohitagg2020** [comment]
During digging down the code, it turns out that NonttyUI gets initiliazed only if we pass the cmd line argument tty as false. Otherwise, as mentioned above, by default it is set to true. 

After discussion with Dmitry, it turns out that only for kapp deploy and delete only, we need the default value as true and for rest of the cases, we can set it as false by default. So, we have to implement this dynamic behavior of checking whether it is `delete or deploy` and then set the default value to false or true. One of the possible place, we can look into for doing this change is EnableTTY() function. Not sure if that will work. But we can also look into the Set method. Both the methods are available in ui_flags.go file.
