### ISSUE TITLE
Target cluster could be highlighted to make it more visible

### ISSUE THREAD

**Issue by renuy** [k14s/kapp#246]
**Describe the problem/challenge you have**
Kapp deploy gives an important information with regards to which cluster is being targeted for deployment.
However, the information is right under command line and there are not highlights.

**Describe the solution you'd like**
target cluster could be made more visible by adding a new line before it, and/or "bold"-ing the information.
 
![image](https://user-images.githubusercontent.com/496363/125397079-11b6f000-e3cb-11eb-9de9-77a85adc956a.png)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by aaronshurley** [comment]
@renuy thanks for bringing up this idea! CLI UX is always a bit tricky to find the right way to display the right information. I haven't thought about this particular bit of information much before since my targeted cluster doesn't change very often. If this information was more visible, what types of use cases do you think would be most beneficial?

cc @cppforlife for any additional context/thoughts

**Comment by boogi** [comment]
@aaronshurley 

I'll piggy back on this one, adding that I'd like to see not only IP (or very long and saying nothing dns name in case of EKS clusters) but also user-friendly name/alias that is set up in .kube/config for a cluster we're operating in.
