### ISSUE TITLE
namespace: components: unable to retrieve the complete list of server APIs

### ISSUE THREAD

**Issue by sanketg86** [k14s/kapp#35]
Error: Applying create certificate/cert-manager-webhook-webhook-tls (certmanager.k8s.io/v1alpha1) namespace: components: unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by cppforlife** [comment]
this is same as this issue: https://github.com/k14s/kapp/issues/12. 

if new APIService is installed and it does not have backing components available, it breaks certain k8s APIs that kapp happens to use (also used by `kubectl api-resources` command).

one way to fix this issue is by making sure that kapp install apiservice backing components before installing APIService itself. to do so one can use kapp ordering directives. ive actually previously installed certmgr this way as shown here: https://github.com/k14s/k8s-resource-protection/tree/master/config-certmanager. this directory can be installed via `ytt -f . --ignore-unknown-comments | kapp deploy -a certmgr -f- -y`.

https://github.com/k14s/k8s-resource-protection/tree/master/config-certmanager/patches.yml makes sure that APIService is installed after deployment+service, and deleted first in case of deletion.

**Comment by cppforlife** [comment]
ill close this in favor of #12.
