### ISSUE TITLE
PVC created via StatefulSet is not deleted automatically during kapp delete

### ISSUE THREAD

**Issue by thmzlt** [k14s/kapp#36]
This is on GKE. I have to go to the Google Cloud console and manually delete the volume claim for the delete operation to finish:

![image](https://user-images.githubusercontent.com/7709/64491701-02a90900-d25b-11e9-8ee8-4b3864a2e1db.png)

**Comment by cppforlife** [comment]
@thmzlt will take a look at it this week or in the beginning of the next.

**Comment by cppforlife** [comment]
according to above diff summary, PersistentVolumeClaim's Op is noop (`-`), hence kapp wont delete it itself, but only will wait for it to be deleted (wait to column says `delete`). that typically happens because kapp wasnt the one to create PVC (StatefulSet creates it; you can see that via kapp inspect, in the column `Owner` it will say `cluster`). it seems that the way k8s works, StatefulSet does not delete "owned" PVC when its deleted (probably to avoid losing data accidently).

i could see kapp adding support for an annotation (eg `kapp.k14s.io/delete-...`) that would force PVC deletion, if PVC was annotated (via StatefulSet PVC configuration). would adding annotation to your StatefulSet PVC configuration be an acceptable solution?

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/kapp/releases/tag/v0.12.0

**Comment by jessehu** [comment]
Related official doc: https://github.com/k14s/kapp/blob/develop/docs/apply.md#kappk14sioowned-for-deletion
