### ISSUE TITLE
kapp should handle imgpkg setups

### ISSUE THREAD

**Issue by jamesdboone** [k14s/kapp#696]
**Describe the problem/challenge you have**
After using kbld to create an imgpkg setup w/ associated image lock file, I can no longer use 'kapp deploy'.
a) it doesn't try to resolve images to associated imagelock files
b) it tries to load the imagelock & bundle files to k8s api, which fails because they aren't crds.

**Describe the solution you'd like**
'kapp deploy' should:
a) use kbld to resolve image references in config.yml
b) know to ignore imagelock and bundle files when creating objects in k8s (don't 'kubectl apply' them)

**Anything else you would like to add:**
Imgpkg documentation references the following kbld syntax, I'm basically asking 'kapp deploy' to behave the same way:
   kbld -f ./config.yml -f .imgpkg/images.yml | kubectl apply -f -

kapp-controller already handles this as per this issue, the kapp binary should also handle it for better integration of toolset:
https://github.com/carvel-dev/kapp-controller/issues/189

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
Hey James! This behaviour is intentional. The individual CLIs are generally unaware of each other but are composable.
What `kapp-controller` does while reconciling is the equivalent of `kbld -f ./config.yml -f .imgpkg/images.yml | kapp deploy -f -`.

If you are looking to test your `kapp-controller` Package/App locally, [`kctrl`](https://carvel.dev/kapp-controller/docs/v0.43.2/kctrl-package-authoring/#testing-packages-locally) might be able to help better. Is this what you are looking for?

**Comment by jamesdboone** [comment]
That makes sense, thanks for the reply!
